#!/bin/bash
#SBATCH -J genOnline1x
#SBATCH -o genOnline1x.o%j
#SBATCH -N 5
#SBATCH --ntasks-per-node 56
#SBATCH -t 24:00:00
#SBATCH -p normal
#SBATCH --mail-type=all
#SBATCH --mail-user=janechen@utexas.edu
module load launcher

export LAUNCHER_WORKDIR=/home1/09498/janechen/MultiExpertHOCAdmission
export LAUNCHER_JOB_FILE=$LAUNCHER_WORKDIR/script/tacc_scripts/genOnline/genOnline1x_job

$LAUNCHER_DIR/paramrun