#!/bin/bash
#SBATCH -J genOnline5x
#SBATCH -o genOnline5x.o%j
#SBATCH -N 2
#SBATCH --ntasks-per-node 56
#SBATCH -t 24:00:00
#SBATCH -p small
#SBATCH --mail-type=all
#SBATCH --mail-user=janechen@utexas.edu
module load launcher

export LAUNCHER_WORKDIR=/home1/09498/janechen/MultiExpertHOCAdmission
export LAUNCHER_JOB_FILE=$LAUNCHER_WORKDIR/script/tacc_scripts/genOnline/genOnline5x_job

$LAUNCHER_DIR/paramrun