#!/bin/bash
#SBATCH -J checkOnline
#SBATCH -o checkOnline.o%j
#SBATCH -N 1
#SBATCH --ntasks-per-node 56
#SBATCH -t 2:00:00
#SBATCH -p small
#SBATCH --mail-type=all
#SBATCH --mail-user=janechen@utexas.edu
module load launcher

export LAUNCHER_WORKDIR=/home1/09498/janechen/MultiExpertHOCAdmission
export LAUNCHER_JOB_FILE=$LAUNCHER_WORKDIR/script/tacc_scripts/checkOnlineResults/checkOnline_job

$LAUNCHER_DIR/paramrun