#!/bin/bash
#SBATCH -J hillclimbing_c20_1x
#SBATCH -o hillclimbing_c20_1x.o%j
#SBATCH -N 6
#SBATCH --ntasks-per-node 56
#SBATCH -t 12:00:00
#SBATCH -p normal
#SBATCH --mail-type=all
#SBATCH --mail-user=janechen@utexas.edu
module load launcher

export LAUNCHER_WORKDIR=/home1/09498/janechen/MultiExpertHOCAdmission
export LAUNCHER_JOB_FILE=$LAUNCHER_WORKDIR/script/tacc_scripts/runHC/hillclimbing_c20_1x_job

$LAUNCHER_DIR/paramrun